export const randomData = {
  images: [
    'https://picsum.photos/100/100/?image=161',
    'https://picsum.photos/100/100/?image=235',
    'https://picsum.photos/100/100/?image=21',
    'https://picsum.photos/100/100/?image=65',
    'https://picsum.photos/100/100/?image=432',
    'https://picsum.photos/100/100/?image=65',
    'https://picsum.photos/100/100/?image=454',
    'https://picsum.photos/100/100/?image=34',
    'https://picsum.photos/100/100/?image=234',
    'https://picsum.photos/100/100/?image=45',
    'https://picsum.photos/100/100/?image=141'
  ],
  names: [
    'Ruth Leach',
    'Humphrey Rodriquez',
    'Head Jefferson',
    'Young Mendez',
    'Viola Lowe',
    'Jennifer Alford',
    'Sue Knapp',
    'Waters Hensley',
    'Moses Yang',
    'Haney Becker',
    'Davis Booker',
    'Craft Buckner',
    'Mcconnell Foley',
    'Shirley Langley',
    'Cornelia Vazquez',
    'Lorrie Sullivan',
    'Johnston Lowe',
    'Pratt Bauer',
    'Rosetta Chandler'
  ],
  titles: [
    'nisi magna',
    'do ipsum',
    'non non',
    'in occaecat',
    'laboris sint',
    'elit laborum',
    'dolor eu',
    'aliquip aliquip',
    'ut eiusmod',
    'officia fugiat',
    'fugiat ipsum',
    'consequat consectetur',
    'labore dolore',
    'voluptate elit',
    'incididunt mollit',
    'excepteur sunt',
    'velit sunt',
    'culpa irure',
    'deserunt culpa',
    'cupidatat sunt'
  ]
};
